---
- name: Install basic tools
  hosts: test
  become: yes
  tasks:
    - name : Install basic tools
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - git
        - curl
        - wget
        - unzip
        - zip
        - python-pip
        - python-dev
