---

- name: Installing Zabbix-Agent Windows

  hosts: all 

  tasks:

    - name: Create directory

      #Crear directorio
      win_file:

        path: C:\Zabbix

        state: directory

    - name: Download Zabbix-Agent

      win_get_url:

        url:  https://cdn.zabbix.com/zabbix/binaries/stable/6.4/6.4.2/zabbix_agent-6.4.2-windows-amd64-openssl.zip

        dest: C:\Zabbix

    - name: Unzip the Zabbix-Agent

      win_shell: tar -xf C:\Zabbix\zabbix_agent-6.4.2-windows-amd64-openssl.zip -C C:\Zabbix


    - name: Modifi the Zabbix-Agentd.conf file

      win_shell: (Get-content  -Path 'C:\Zabbix\conf\zabbix_agentd.conf' ).replace('Server=127.0.0.1','Server=192.168.122.1') | Set-Content C:\Zabbix\conf\zabbix_agentd.conf



    - name: Install Zabbix-Agent

      win_shell: C:\Zabbix\bin\zabbix_agentd.exe --config C:\Zabbix\conf\zabbix_agentd.conf --install

    - name: Start Zabbix-Agent

      win_service:

        win_shell: C:\Zabbix\bin\zabbix_agentd.exe --start